### ISSUE TITLE
Problem bei Kommazahlen

### ISSUE THREAD

**Issue by hprien** [SimonJpg2/Praktikum2-pg1-hda#1]
Bei mir hat es so nicht mit Kommazahlen für a funktioniert.\
Das Programm fiel da in eine Endlosschleife.
https://github.com/SimonJpg2/Praktikum2-pg1-hda/blob/b939716e060042f8ffedde10f751a6a9dee12226/main.cpp#L89
Ich habe die Zahlen nach einigen Stellen abgebrochen und dann verglichen:\
`while((int)(x * 10000) > (int)(y * 10000))`\
Schöner wäre es vermutlich zu runden statt abzubrechen.

**Comment by SimonJpg2** [comment]
Nach mehrfachem Testen konnte ich den bug leider nicht reproduzieren. 

Bei mir kommt bei der Eingabe `500.342` das Ergebnis `22.3683` heraus.

Welche Werte hattest du eingegeben, die dann zu einer Endlosschleife geführt haben?

**Comment by SimonJpg2** [comment]
Ich habe den Datentyp `double` durch `float` ersetzt, womit der Bug gefixt sein sollte. Leider habe ich immer noch keine Ahnung, warum es mit einem float geht, mit double jedoch nicht haha
